test fuiled

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -50,7 +50,8 @@ jobs:
           path: dist/
 
   deploy:
-    if: github.ref == 'refs/heads/main'
+    # if: github.ref == 'refs/heads/main'
+    if: success()
     runs-on: ubuntu-latest
     needs:
       - build
@@ -63,3 +64,20 @@ jobs:
         run: ls -R
       - name: Deploy
         run: echo "Deploying..."
+      - name: force fuiled
+        run: exit 1
+
+  # Runs only if tests fail
+  notify-failure:
+    needs: 
+      - build
+      - deploy
+    if: failure()
+    runs-on: ubuntu-latest
+    steps:
+      - name: Discord notification
+        env:
+          DISCORD_WEBHOOK: https://discord.com/api/webhooks/1421591330534195294/mPE6czOkHtNuMeKn_U8_HToha1UhtGxilcTXEhTKt4yUo8EjGLPcMQI553WgkK-kf8Ez
+        uses: Ilshidur/action-discord@master
+        with:
+          args: 'Build fuiled ..'
